### ISSUE TITLE
Randomized Event Groups not Working properly

### ISSUE THREAD

**Issue by GR-Sauron** [GlowPuff/JiMEditor#3]
See attached campaign.  The scenario in question is named 
'Lady Elderath.  The Tile block 'The Wilds' is made of 5 random tiles.  The Tile block is configured to use the event group 'GRP1'  The tile block properly picks up that I have 8 events defined for this group, with the tile block configured to randomly use 5 out of these 8 events.  In play-testing though, the same 5 events are always used, and these 5 events always appear on the same tiles over multiple play tests.  The 5 events that appear are the first 5 events belonging to the GRP1 group as they appear in the 'Events' dropdown field.

[Lord of The Ozarks.zip](https://github.com/GlowPuff/JiMEditor/files/11760332/Lord.of.The.Ozarks.zip)

**Comment by GlowPuff** [comment]
Hello Sauron!  I'm sorry to say, I don't maintain this project anymore.  I think this guy is currently working on it: 
https://github.com/TrnsltLife
